# Generated by Django 5.0 on 2026-04-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='temperature',
            field=models.FloatField(default=0.2),
        ),
    ]
