# Generated by Django 5.2.12 on 2026-04-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chat_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_time',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='token_used',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
