# Generated by Django 5.2.12 on 2026-04-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_message_question_intent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ragquerylog',
            new_name='home_ragque_questio_438581_idx',
            old_name='home_ragque_questio_idx',
        ),
    ]
