# Generated by Django 5.0 on 2026-04-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_home_ragque_questio_idx_home_ragque_questio_438581_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
